//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Meeting
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idMeeting { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual NUser NUser { get; set; }
    }
}
